version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/backend
    environment:
      - FLASK_ENV=development

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/frontend
    stdin_open: true
    tty: true
    depends_on:
      - backend

  tf-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - type: bind
        source: C:/_uni/ecg-app-git/models/gen_model_36
        target: /models/gan_model1
      - type: bind
        source: C:/_uni/ecg-app-git/models/gen_model_50
        target: /models/gan_model2
      - type: bind
        source: C:/_uni/ecg-app-git/models/models.config
        target: /models/models.config
    
    command: tensorflow/serving --model_config_file=/models/models.config